name: snip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  code_text_field: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_highlight: ^0.7.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
